logging:
    level:
        org:
            hibernate:
                SQL: debug
                type:
                    descriptor: trace
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost:3306/mobilelele?createDatabaseIfNotExist=true
        username: root
    jpa:
#        The DB will be instasiate first before inserst
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
    sql:
        init:
            mode: never
