logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor: trace
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/hateoas?createDatabaseIfNotExist=true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
